version: '3.1'
services:
  ns-database:
    image: mysql:5.7
    ports:
      - "3333:3306"
    environment:
      MYSQL_DATABASE: "ns-database"
      MYSQL_ROOT_PASSWORD: "bPS26jR2qkQvx5A"
    volumes:
      - ns-database-data:/var/lib/mysql
volumes:
  ns-database-data: